ALTER TABLE BATCH_JOB_EXECUTION DROP COLUMN JOB_CONFIGURATION_LOCATION;

ALTER SEQUENCE BATCH_STEP_EXECUTION_SEQ ORDER;
ALTER SEQUENCE BATCH_JOB_EXECUTION_SEQ ORDER;
ALTER SEQUENCE BATCH_JOB_SEQ ORDER;

ALTER TABLE BATCH_STEP_EXECUTION MODIFY CREATE_TIME TIMESTAMP DEFAULT TO_TIMESTAMP('1970-01-01 00:00:00', 'yyyy-MM-dd HH24:mi:ss') NOT NULL;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS MODIFY PARAMETER_TYPE VARCHAR(100);
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS MODIFY PARAMETER_NAME VARCHAR(100);
ALTER TABLE BATCH_JOB_EXECUTION_PARAMS MODIFY PARAMETER_VALUE VARCHAR(2500);

ALTER TABLE BATCH_JOB_EXECUTION MODIFY CREATE_TIME TIMESTAMP(9);
ALTER TABLE BATCH_JOB_EXECUTION MODIFY START_TIME TIMESTAMP(9);
ALTER TABLE BATCH_JOB_EXECUTION MODIFY END_TIME TIMESTAMP(9);
ALTER TABLE BATCH_JOB_EXECUTION MODIFY LAST_UPDATED TIMESTAMP(9);

ALTER TABLE BATCH_STEP_EXECUTION MODIFY CREATE_TIME TIMESTAMP(9);
ALTER TABLE BATCH_STEP_EXECUTION MODIFY START_TIME TIMESTAMP(9);
ALTER TABLE BATCH_STEP_EXECUTION MODIFY END_TIME TIMESTAMP(9);
ALTER TABLE BATCH_STEP_EXECUTION MODIFY LAST_UPDATED TIMESTAMP(9);



