ALTER TABLE API_GRAD_BATCH.BATCH_JOB_TYPE_CODE MODIFY BATCH_JOB_TYPE_CODE VARCHAR2(20);
ALTER TABLE API_GRAD_BATCH.BATCH_JOB_TYPE_CODE MODIFY LABEL VARCHAR2(75);
ALTER TABLE API_GRAD_BATCH.BATCH_JOB_TYPE_CODE MODIFY DESCRIPTION VARCHAR2(350);
