ALTER TABLE BATCH_JOB_EXECUTION_PARAMS RENAME TO BATCH_JOB_EXECUTION_PARAMS_OLD;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
                                             JOB_EXECUTION_ID NUMBER(19,0) NOT NULL ,
                                             PARAMETER_TYPE VARCHAR2(32 char) NOT NULL ,
                                             PARAMETER_NAME VARCHAR2(100 char) NOT NULL ,
                                             PARAMETER_VALUE VARCHAR2(1000 char) ,
                                             IDENTIFYING CHAR(1) NOT NULL
);

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS
    ADD CONSTRAINT BATCH_JOB_EXECUTION_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
        REFERENCES BATCH_JOB_EXECUTION (JOB_EXECUTION_ID) DISABLE;

INSERT INTO BATCH_JOB_EXECUTION_PARAMS (
    JOB_EXECUTION_ID,
    PARAMETER_TYPE,
    PARAMETER_NAME,
    PARAMETER_VALUE,
    IDENTIFYING
) SELECT
      JOB_EXECUTION_ID,
      CASE
          WHEN TYPE_CD = 'STRING' THEN 'java.lang.String'
          WHEN TYPE_CD = 'LONG' THEN 'java.lang.Long'
          WHEN TYPE_CD = 'DOUBLE' THEN 'java.lang.Double'
          ELSE 'java.lang.String'
          END TYPE_CD,
      KEY_NAME,
      CASE
          WHEN TYPE_CD = 'STRING' THEN STRING_VAL
          WHEN TYPE_CD = 'LONG' THEN TO_CHAR(LONG_VAL)
          WHEN TYPE_CD = 'DOUBLE' THEN TO_CHAR(DOUBLE_VAL)
          ELSE STRING_VAL
          END STRING_VAL,
      IDENTIFYING
FROM BATCH_JOB_EXECUTION_PARAMS_OLD;

COMMIT;

ALTER TABLE BATCH_JOB_EXECUTION_PARAMS MODIFY CONSTRAINT BATCH_JOB_EXECUTION_PARAMS_FK ENABLE NOVALIDATE;

ALTER TABLE BATCH_STEP_EXECUTION ADD CREATE_TIME TIMESTAMP;
ALTER TABLE BATCH_STEP_EXECUTION MODIFY (START_TIME NULL);
ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT MODIFY (SHORT_CONTEXT NULL);
ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT MODIFY (SHORT_CONTEXT NULL);



