-- Spring Batch Tables alteration to move tablespace for CLOB

ALTER TABLE BATCH_STEP_EXECUTION_CONTEXT
    MOVE LOB ("SERIALIZED_CONTEXT") STORE AS SECUREFILE (
    TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW CHUNK 8192
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES);

ALTER TABLE BATCH_JOB_EXECUTION_CONTEXT
    MOVE LOB ("SERIALIZED_CONTEXT") STORE AS SECUREFILE (
    TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW CHUNK 8192
    NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES);

