-- API_GRAD_BATCH.STUDENT_CREDENTIAL_DISTRIBUTION definition

CREATE TABLE "STUDENT_CREDENTIAL_DISTRIBUTION"
(	"STUDENT_CREDENTIAL_DISTRIBUTION_ID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
     "JOB_EXECUTION_ID" NUMBER(19,0) NOT NULL ENABLE,
     "GRADUATION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
     "BATCH_JOB_TYPE_CODE" VARCHAR2(15 BYTE),
     "SCHOOL_OF_RECORD" VARCHAR2(9 BYTE),
     "PAYLOAD" CLOB,
     "STATUS" VARCHAR2(10 BYTE),
     "ERROR" VARCHAR2(1000 BYTE),
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "STUDENT_CREDENTIAL_DISTRIBUTION_PK" PRIMARY KEY ("STUDENT_CREDENTIAL_DISTRIBUTION_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "BAT_SCD_DIST_JBEXEC_FK" FOREIGN KEY ("JOB_EXECUTION_ID")
         REFERENCES "BATCH_JOB_EXECUTION" ("JOB_EXECUTION_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY
 LOB ("PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES
  STORAGE(INITIAL 262144 NEXT 262144 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
;