CREATE INDEX X_BATCH_STUD_JOB_ID_STAT
ON BATCH_GRAD_ALG_STUDENT (
    JOB_EXECUTION_ID, STATUS
)
TABLESPACE API_GRAD_IDX;

CREATE INDEX X_BATCH_STUD_JOB_ID
ON BATCH_GRAD_ALG_STUDENT (JOB_EXECUTION_ID)
TABLESPACE API_GRAD_IDX;

CREATE INDEX X_BATCH_STUD_STUDID_JOB_ID
ON BATCH_GRAD_ALG_STUDENT (
    GRADUATION_STUDENT_RECORD_ID
    ,JOB_EXECUTION_ID
)
TABLESPACE API_GRAD_IDX;

