INSERT INTO BATCH_JOB_TYPE_CODE (BATCH_JOB_TYPE_CODE,LABEL,DESCRIPTION,DISPLAY_ORDER,EFFECTIVE_DATE,EXPIRY_DATE)
VALUES ('TVR_DELETE','Delete Student TVR Process','A year-end process that will delete student TVRs',120,TIMESTAMP'2024-06-24  00:00:00.0',NULL);
