
CREATE OR REPLACE EDITIONABLE SYNONYM "TRAX_STUDENTS_LOAD" FOR "TRAX_STUDENTS_LOAD"@"TRAXLINK.WORLD";

CREATE OR REPLACE EDITIONABLE SYNONYM "STUDENT_MASTER" FOR "STUDENT_MASTER"@"TRAXLINK.WORLD";

CREATE OR REPLACE EDITIONABLE SYNONYM "TAB_CRSE" FOR "TAB_CRSE"@"TRAXLINK.WORLD";