GRANT SELECT ON BATCH_JOB_INSTANCE TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION TO GRAD_READONLY;
GRANT SELECT ON BATCH_STEP_EXECUTION TO GRAD_READONLY;
GRANT SELECT ON BATCH_STEP_EXECUTION_CONTEXT TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION_CONTEXT TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION_PARAMS TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_TRIGGER_CODE TO GRAD_READONLY;
GRANT SELECT ON BATCH_GRAD_ALGORITHM_JOB_HISTORY TO GRAD_READONLY;
