-- API_GRAD_DATA_CONV.BATCH_SHEDLOCK definition

CREATE TABLE "BATCH_SHEDLOCK"
   (	"NAME" VARCHAR2(64),
	"LOCK_UNTIL" TIMESTAMP (3),
	"LOCKED_AT" TIMESTAMP (3),
	"LOCKED_BY" VARCHAR2(255),
	 CONSTRAINT "BATCH_SHEDLOCK_PK" PRIMARY KEY ("NAME")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

COMMENT ON TABLE BATCH_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';