-- API_GRAD_BATCH.BATCH_GRAD_ALG_STUDENT definition

CREATE TABLE "BATCH_GRAD_ALG_STUDENT"
(	"BATCH_GRAD_ALG_STUDENT_ID" RAW(16) DEFAULT SYS_GUID() NOT NULL ENABLE,
     "GRADUATION_STUDENT_RECORD_ID" RAW(16) NOT NULL ENABLE,
     "JOB_EXECUTION_ID" NUMBER(19,0) NOT NULL ENABLE,
     "GRADUATION_PROGRAM_CODE" VARCHAR2(8 BYTE),
     "SCHOOL_OF_RECORD" VARCHAR2(9 BYTE),
     "STATUS" VARCHAR2(10 BYTE),
     "ERROR" VARCHAR2(1000 BYTE),
     "CREATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "CREATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     "UPDATE_USER" VARCHAR2(32) DEFAULT USER NOT NULL ENABLE,
     "UPDATE_DATE" DATE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
     CONSTRAINT "BATCH_GRAD_ALG_STUDENT_PK" PRIMARY KEY ("BATCH_GRAD_ALG_STUDENT_ID")
         USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
     CONSTRAINT "BAT_GRDALG_STUDENT_JBEXEC_FK" FOREIGN KEY ("JOB_EXECUTION_ID")
         REFERENCES "BATCH_JOB_EXECUTION" ("JOB_EXECUTION_ID") ENABLE
) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;