GRANT SELECT ON BATCH_GRAD_ALG_STUDENT TO GRAD_READONLY;
GRANT SELECT ON BATCH_GRAD_ALGORITHM_JOB_HISTORY TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION_CONTEXT TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_EXECUTION_PARAMS TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_INSTANCE TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_TRIGGER_CODE TO GRAD_READONLY;
GRANT SELECT ON BATCH_JOB_TYPE_CODE TO GRAD_READONLY;
GRANT SELECT ON BATCH_PROCESSING TO GRAD_READONLY;
GRANT SELECT ON BATCH_SHEDLOCK TO GRAD_READONLY;
GRANT SELECT ON BATCH_STEP_EXECUTION TO GRAD_READONLY;
GRANT SELECT ON BATCH_STEP_EXECUTION_CONTEXT TO GRAD_READONLY;
GRANT SELECT ON FLYWAY_SCHEMA_HISTORY TO GRAD_READONLY;
GRANT SELECT ON STUDENT_CREDENTIAL_DISTRIBUTION TO GRAD_READONLY;
GRANT SELECT ON USER_SCHEDULED_JOBS TO GRAD_READONLY;


