ALTER TABLE BATCH_GRAD_ALG_STUDENT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE BATCH_GRAD_ALG_STUDENT
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE BATCH_GRAD_ALGORITHM_JOB_HISTORY
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE BATCH_GRAD_ALGORITHM_JOB_HISTORY
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE BATCH_JOB_TRIGGER_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE BATCH_JOB_TRIGGER_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE BATCH_JOB_TYPE_CODE
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE BATCH_JOB_TYPE_CODE
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE BATCH_PROCESSING
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE BATCH_PROCESSING
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_CREDENTIAL_DISTRIBUTION
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE STUDENT_CREDENTIAL_DISTRIBUTION
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE USER_SCHEDULED_JOBS
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE USER_SCHEDULED_JOBS
    MODIFY UPDATE_USER VARCHAR2(100);





