#DB Properties
spring:
  jmx:
    enabled: false
  db-connection:
    hikari:
      pool-name: educ-grad-batch-graduation-api-cp
      maximum-pool-size: ${MAXIMUM_POOL_SIZE}
      connection-timeout: ${CONNECTION_TIMEOUT}
      max-lifetime: ${MAX_LIFETIME}
      minimum-idle: 2
      keepalive-time: ${KEEP_ALIVE_TIME}
      idle-timeout: ${IDLE_TIMEOUT}
    url: ${CONNECTION_STRING}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
  mvc:
    log-request-details: ${SPRING_SHOW_REQUEST_DETAILS}
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  #Keycloak/OAuth properties
  security:
    user:
      name: ${API_USERNAME}
      password: ${API_PASSWORD}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${TOKEN_ISSUER_URL}
          jwk-set-uri: ${TOKEN_ISSUER_URL}/protocol/openid-connect/certs
  batch:
    initialize-schema: NEVER
    job:
      enabled: false
  flyway:
    enabled: ${ENABLE_FLYWAY}
    baseline-on-migrate: false
    table: FLYWAY_SCHEMA_HISTORY
    url: ${CONNECTION_STRING}
    schema: ${USERNAME}
    user: ${USERNAME}
    password: ${PASSWORD}
    location: classpath:db/migration

#Logging properties
logging:
  file:
    max-history: 1
    clean-history-on-start: true
    max-size: 20MB
    name: /logs/app.log
  #pattern:
  #  file: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  #  console: %d | [${HOSTNAME}] | %clr(%5p) | [%t]   | %logger{36}:%L | %msg%n
  level:
    ca:
      bc:
        gov:
          educ:
            api:
              batchgraduation: ${APP_LOG_LEVEL}
    org:
      springframework:
        web: ${SPRING_WEB_LOG_LEVEL}
        security: ${SPRING_SECURITY_LOG_LEVEL}
        boot:
          autoconfigure:
            logging: ${SPRING_BOOT_AUTOCONFIG_LOG_LEVEL}
    com:
      zaxxer:
        hikari: ERROR

#Local properties
server:
  undertow:
    threads:
      worker: 128
      io: 16
  #port: ${HTTP_PORT}

#API Documentation
springdoc:
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/api-docs-ui.html
    operationsSorter: alpha

#Resilience
resilience4j.retry:
  instances:
    rt-getToken:
      maxAttempts: 35
      waitDuration: 5s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    reggradrun:
      maxAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 2s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    tvrrun:
      maxAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 2s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException
    rt-getStudent:
      maxAttempts: ${MAX_RETRY_ATTEMPTS}
      waitDuration: 2s
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
      ignoreExceptions:
        - java.lang.NullPointerException

authorization:
  user: ${GRAD_CLIENT_NAME}
  password: ${GRAD_CLIENT_SECRET}

batch:
  partitions:
    number: ${NUMBER_OF_PARTITIONS}
  regalg:
    cron: ${REG_ALG_CRON}
  tvrrun:
    cron: ${TVR_RUN_CRON}
  distrun:
    cron: ${DIST_RUN_CRON}
  token-expiry:
    offset: ${TOKEN_EXPIRY_OFFSET}

#Endpoints
endpoint:
  keycloak:
    getToken: ${KEYCLOAK_TOKEN_URL}auth/realms/master/protocol/openid-connect/token
  grad-graduation-api:
    graduatestudent: 
      url: ${GRAD_GRADUATION_API}api/v1/graduate/studentid/%s/run/GS?batchId=%s
    reportonlyrun: 
      url: ${GRAD_GRADUATION_API}api/v1/graduate/studentid/%s/run/FMR?batchId=%s
    tvrrun:
      url: ${GRAD_GRADUATION_API}api/v1/graduate/studentid/%s/run/REGFM?batchId=%s
    schoolreport:
      url: ${GRAD_GRADUATION_API}api/v1/graduate/report/school?type=%s
  grad-student-api:
    grad-status: ${GRAD_STUDENT_API}api/v1/student/studentid/%s
    student-for-grad-list: ${GRAD_STUDENT_API}api/v1/student/recalculate
    student-for-projectedgrad-list: ${GRAD_STUDENT_API}api/v1/student/projected
    get-student-for-batch-input: ${GRAD_STUDENT_API}api/v1/student/batch/gradstudent/studentid/%s
    pen-student-by-pen: ${PEN_API}api/v1/student?pen=%s
    student-for-special-grad-run-list: ${GRAD_STUDENT_API}api/v1/student/studentlistsearch
    get-student-data-list: ${GRAD_STUDENT_API}api/v1/student/multistudentids
    get-student-record: ${GRAD_STUDENT_API}api/v1/student/grad/%s
    update-student-record: ${GRAD_STUDENT_API}api/v1/student/distribution/studentid/%s?batchId=%s&activityCode=%s
    read-grad-student-record: ${GRAD_STUDENT_API}api/v1/student/studentid/%s/algorithm
    read-grad-student-record-batch: ${GRAD_STUDENT_API}api/v1/student/batch/%s
    update-flag-ready-for-batch: ${GRAD_STUDENT_API}api/v1/student/multistudentids/batchflag/jobtype/%s
  grad-graduation-report-api:
    get-transcript-list:
      yearly:
        url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/gettranscriptsfordistributionyearly
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/gettranscriptsfordistribution
    get-certificate-list:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/getcertificatesfordistribution
    update-student-credential:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/studentcredential?studentID=%s&credentialTypeCode=%s&paperType=%s&documentStatusCode=%s&activityCode=%s
    user-req-dis-run:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/userrequest/%s
    get-certificate-types:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/certificatetype/%s
    update-school-report:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/updateschoolreport?mincode=%s&reportTypeCode=%s
    get-school-report-list:
      url: ${GRAD_GRADUATION_REPORT_API}api/v1/graduationreports/schoolreportdistribution
  grad-distribution-api:
    merge-n-upload:
      url: ${GRAD_DISTRIBUTION_API}api/v1/distribute/run/MER?batchId=%s&activityCode=%s&localDownload=%s
    merge-n-upload-yearly:
      url: ${GRAD_DISTRIBUTION_API}api/v1/distribute/run/MERYER?batchId=%s&activityCode=%s
    reprint-n-upload:
      url: ${GRAD_DISTRIBUTION_API}api/v1/distribute/run/RPR?batchId=%s&activityCode=%s&localDownload=%s
    blanks-n-upload:
      url: ${GRAD_DISTRIBUTION_API}api/v1/distribute/run/BCPR?batchId=%s&localDownload=%s
    read-n-post:
      url: ${GRAD_DISTRIBUTION_API}api/v1/distribute/run/PSR?batchId=%s
    merge-psi-n-upload:
      url: ${GRAD_DISTRIBUTION_API}api/v1/distribute/run/PSPR?batchId=%s&localDownload=%s
  grad-trax-api:
    get-psi-student-list:
      url: ${GRAD_TRAX_API}api/v1/trax/psi/student?transmissionMode=%s&psiCode=%s&psiYear=%s
